"""Add is_default to Signature

Revision ID: 4f1235004153
Revises: b57ca14c70ee
Create Date: 2025-06-30 09:49:42.690809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1235004153'
down_revision = 'b57ca14c70ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signature', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
