"""add document details fields (client, work, document_type, comment)

Revision ID: b57ca14c70ee
Revises: d1cc1c89615a
Create Date: 2025-06-26 11:05:03.213017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57ca14c70ee'
down_revision = 'd1cc1c89615a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('work', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('document_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('document_type')
        batch_op.drop_column('work')
        batch_op.drop_column('client')

    # ### end Alembic commands ###
