"""Add signature_type to Signature

Revision ID: d1cc1c89615a
Revises: c1eb75aae189
Create Date: 2025-05-15 09:21:01.817817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cc1c89615a'
down_revision = 'c1eb75aae189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('display_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signature', schema=None) as batch_op:
        batch_op.drop_column('display_name')
        batch_op.drop_column('signature_type')

    # ### end Alembic commands ###
